#!/bin/bash
title="Arcris Install"

msg_part_select="Select disk"
msg_part_select_disk="Select your disk"
msg_part_select_arch="\nSelect disk for Arch Linux\n "

auto1 () {


################################################################
# SELETC DISK
################################################################

part="$(lsblk -lno NAME,SIZE,TYPE | grep 'disk' | awk '{print "/dev/" $1 " " $2}' | sort -u | sed '/f/d' | sed '/sr/d' )" 
disk=$(dialog --backtitle "${title}" --clear  --ok-label "${msg_part_select}" --no-cancel --menu "${msg_part_select_arch}" 12 45 0 ${part} 2>&1 >/dev/tty)

}
auto1